In [1]:
from non_parametric_pro.density import normal_logpdf, ProParameters, pro_replica_fn
import jax

import jax.numpy as jnp

In [31]:
n = 100
c = 10.0

lambda_n = c * jnp.sqrt(n)

alpha = lambda_n / n

print(alpha)

1.0


In [52]:
jnp.exp(jnp.log(c) + 3)

Array(635.16034, dtype=float32, weak_type=True)

In [9]:
1 / 100

0.01

In [26]:
particles = jax.random.normal(jax.random.PRNGKey(0), (3, 2))

y = jnp.array([[1.0], [2.0], [3.0]])

sigma = 0.5

parameters = ProParameters(
    y=y,
    step_size=0.1,
    sigma=sigma,
    alpha=1.0,
    tolerance=1e-300,
)

normal_logpdf(y, particles, sigma)

Array([[ -1.0011579,  -2.328127 ],
       [-12.070556 ,  -8.867091 ],
       [-16.174715 , -31.780777 ]], dtype=float32)

In [29]:
marginal = pro_replica_fn(particles, parameters)
jnp.exp(marginal).sum(axis=1)

Array([1.       , 1.       , 1.0000001], dtype=float32)

In [31]:
dens = jnp.exp(normal_logpdf(y, particles, sigma))
dens = dens / jnp.sum(dens, axis=1, keepdims=True)
dens.sum(axis=1)

Array([1., 1., 1.], dtype=float32)